name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: [krlosMata, laisolizq, invocamanman, ignasirv]
body:
  - type: markdown
    attributes:
      value: |
        Fill in all necessary information to report a bug
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using ?
      placeholder: 'ex: v1.0.0'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain the bug found and the expected result
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please share detailed information about ho to reproduce the bug
    validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log
      description: Please copy and paste any relevant log output
      render: shell