name: Feature Request
description: File a bug report
title: "[Feature]: "
labels: ["feature"]
assignees:
  - krlosMata
body:
  - type: markdown
    attributes:
      value: |
        Fill in all necessary information to request a feature
  - type: input
    id: version
    attributes:
      label: Version
      description: What version the features should be added ?
      placeholder: 'ex: v1.0.0'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain the feature
    validations:
      required: true