name: Question
description: Submit a question
title: "[Question]: "
labels: ["question"]
assignees:
  - krlosMata
body:
  - type: markdown
    attributes:
      value: |
        Fill in all necessary information to submit a question
  - type: input
    id: version
    attributes:
      label: Version
      description: What version the question is refering to ?
      placeholder: 'ex: v1.0.0'
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Description
      description: Explain the question
    validations:
      required: true